/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SunRouteImport } from './routes/sun'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosNewRouteImport } from './routes/todos/new'
import { Route as AiSdkStructuredDataStreamRouteImport } from './routes/ai-sdk/structured-data-stream'
import { Route as AiSdkMsgRouteImport } from './routes/ai-sdk/msg'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as PostsPostIdSplatRouteImport } from './routes/posts/$postId/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSdkStructuredRouteImport } from './routes/api/ai-sdk/structured'
import { Route as ApiAiSdkSentimentRouteImport } from './routes/api/ai-sdk/sentiment'
import { Route as ApiAiSdkChatRouteImport } from './routes/api/ai-sdk/chat'

const SunRoute = SunRouteImport.update({
  id: '/sun',
  path: '/sun',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSdkStructuredDataStreamRoute =
  AiSdkStructuredDataStreamRouteImport.update({
    id: '/ai-sdk/structured-data-stream',
    path: '/ai-sdk/structured-data-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiSdkMsgRoute = AiSdkMsgRouteImport.update({
  id: '/ai-sdk/msg',
  path: '/ai-sdk/msg',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PostsPostIdSplatRoute = PostsPostIdSplatRouteImport.update({
  id: '/$postId/$',
  path: '/$postId/$',
  getParentRoute: () => PostsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSdkStructuredRoute = ApiAiSdkStructuredRouteImport.update({
  id: '/api/ai-sdk/structured',
  path: '/api/ai-sdk/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSdkSentimentRoute = ApiAiSdkSentimentRouteImport.update({
  id: '/api/ai-sdk/sentiment',
  path: '/api/ai-sdk/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSdkChatRoute = ApiAiSdkChatRouteImport.update({
  id: '/api/ai-sdk/chat',
  path: '/api/ai-sdk/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/sun': typeof SunRoute
  '/ai-sdk/msg': typeof AiSdkMsgRoute
  '/ai-sdk/structured-data-stream': typeof AiSdkStructuredDataStreamRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/': typeof TodosIndexRoute
  '/api/ai-sdk/chat': typeof ApiAiSdkChatRoute
  '/api/ai-sdk/sentiment': typeof ApiAiSdkSentimentRoute
  '/api/ai-sdk/structured': typeof ApiAiSdkStructuredRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/$postId/$': typeof PostsPostIdSplatRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/sun': typeof SunRoute
  '/ai-sdk/msg': typeof AiSdkMsgRoute
  '/ai-sdk/structured-data-stream': typeof AiSdkStructuredDataStreamRoute
  '/todos/new': typeof TodosNewRoute
  '/todos': typeof TodosIndexRoute
  '/api/ai-sdk/chat': typeof ApiAiSdkChatRoute
  '/api/ai-sdk/sentiment': typeof ApiAiSdkSentimentRoute
  '/api/ai-sdk/structured': typeof ApiAiSdkStructuredRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/$postId/$': typeof PostsPostIdSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/practice': typeof PracticeRoute
  '/sun': typeof SunRoute
  '/ai-sdk/msg': typeof AiSdkMsgRoute
  '/ai-sdk/structured-data-stream': typeof AiSdkStructuredDataStreamRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/': typeof TodosIndexRoute
  '/api/ai-sdk/chat': typeof ApiAiSdkChatRoute
  '/api/ai-sdk/sentiment': typeof ApiAiSdkSentimentRoute
  '/api/ai-sdk/structured': typeof ApiAiSdkStructuredRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/$postId/$': typeof PostsPostIdSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/about'
    | '/dashboard'
    | '/practice'
    | '/sun'
    | '/ai-sdk/msg'
    | '/ai-sdk/structured-data-stream'
    | '/todos/new'
    | '/todos/'
    | '/api/ai-sdk/chat'
    | '/api/ai-sdk/sentiment'
    | '/api/ai-sdk/structured'
    | '/api/auth/$'
    | '/posts/$postId/$'
    | '/login/'
    | '/signup/'
    | '/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts'
    | '/about'
    | '/dashboard'
    | '/practice'
    | '/sun'
    | '/ai-sdk/msg'
    | '/ai-sdk/structured-data-stream'
    | '/todos/new'
    | '/todos'
    | '/api/ai-sdk/chat'
    | '/api/ai-sdk/sentiment'
    | '/api/ai-sdk/structured'
    | '/api/auth/$'
    | '/posts/$postId/$'
    | '/login'
    | '/signup'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/posts'
    | '/about'
    | '/dashboard'
    | '/practice'
    | '/sun'
    | '/ai-sdk/msg'
    | '/ai-sdk/structured-data-stream'
    | '/todos/new'
    | '/todos/'
    | '/api/ai-sdk/chat'
    | '/api/ai-sdk/sentiment'
    | '/api/ai-sdk/structured'
    | '/api/auth/$'
    | '/posts/$postId/$'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  PracticeRoute: typeof PracticeRoute
  SunRoute: typeof SunRoute
  AiSdkMsgRoute: typeof AiSdkMsgRoute
  AiSdkStructuredDataStreamRoute: typeof AiSdkStructuredDataStreamRoute
  TodosNewRoute: typeof TodosNewRoute
  TodosIndexRoute: typeof TodosIndexRoute
  ApiAiSdkChatRoute: typeof ApiAiSdkChatRoute
  ApiAiSdkSentimentRoute: typeof ApiAiSdkSentimentRoute
  ApiAiSdkStructuredRoute: typeof ApiAiSdkStructuredRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sun': {
      id: '/sun'
      path: '/sun'
      fullPath: '/sun'
      preLoaderRoute: typeof SunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sdk/structured-data-stream': {
      id: '/ai-sdk/structured-data-stream'
      path: '/ai-sdk/structured-data-stream'
      fullPath: '/ai-sdk/structured-data-stream'
      preLoaderRoute: typeof AiSdkStructuredDataStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sdk/msg': {
      id: '/ai-sdk/msg'
      path: '/ai-sdk/msg'
      fullPath: '/ai-sdk/msg'
      preLoaderRoute: typeof AiSdkMsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/posts/$postId/$': {
      id: '/posts/$postId/$'
      path: '/$postId/$'
      fullPath: '/posts/$postId/$'
      preLoaderRoute: typeof PostsPostIdSplatRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-sdk/structured': {
      id: '/api/ai-sdk/structured'
      path: '/api/ai-sdk/structured'
      fullPath: '/api/ai-sdk/structured'
      preLoaderRoute: typeof ApiAiSdkStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-sdk/sentiment': {
      id: '/api/ai-sdk/sentiment'
      path: '/api/ai-sdk/sentiment'
      fullPath: '/api/ai-sdk/sentiment'
      preLoaderRoute: typeof ApiAiSdkSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-sdk/chat': {
      id: '/api/ai-sdk/chat'
      path: '/api/ai-sdk/chat'
      fullPath: '/api/ai-sdk/chat'
      preLoaderRoute: typeof ApiAiSdkChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdSplatRoute: typeof PostsPostIdSplatRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdSplatRoute: PostsPostIdSplatRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  PracticeRoute: PracticeRoute,
  SunRoute: SunRoute,
  AiSdkMsgRoute: AiSdkMsgRoute,
  AiSdkStructuredDataStreamRoute: AiSdkStructuredDataStreamRoute,
  TodosNewRoute: TodosNewRoute,
  TodosIndexRoute: TodosIndexRoute,
  ApiAiSdkChatRoute: ApiAiSdkChatRoute,
  ApiAiSdkSentimentRoute: ApiAiSdkSentimentRoute,
  ApiAiSdkStructuredRoute: ApiAiSdkStructuredRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
